# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merk_auto', models.CharField(max_length=50)),
                ('type_auto', models.CharField(max_length=50)),
                ('brandstof', models.CharField(max_length=50)),
                ('kleur', models.CharField(max_length=50)),
                ('bouwjaar', models.IntegerField()),
                ('prijs', models.IntegerField()),
            ],
        ),
    ]
