# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_automerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='merk_auto',
            field=models.CharField(choices=[('Audi', 'Audi'), ('Bmw', 'Bmw'), ('Mercedes', 'Mercedes'), ('Volvo', 'Volvo'), ('Volkswagen', 'Volkswagen'), ('Opel', 'Opel'), ('Suzuki', 'Suzuki'), ('Citroen', 'Citroen'), ('Peugeot', 'Peugeot')], default='Audi', max_length=9),
        ),
    ]
