# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20161216_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automerk',
            old_name='merk',
            new_name='type_auto',
        ),
    ]
