# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20161216_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='kleur',
            field=models.CharField(choices=[('Zwart', 'Zwart'), ('Blauw', 'Blauw'), ('Grijs', 'Grijs'), ('Wit', 'Wit'), ('Groen', 'Groen'), ('Geel', 'Geel'), ('Roze', 'Roze'), ('Roze', 'Rood')], default='Zwart', max_length=50),
        ),
    ]
