# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20161219_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automerk',
            name='type_auto',
        ),
        migrations.DeleteModel(
            name='Automerk',
        ),
    ]
