# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_auto_20161222_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='image',
            field=models.ImageField(default=False, upload_to='autoimages/'),
        ),
    ]
